* Dodcott-cum-Wilkesley Web Site.
This is the source for the Parish of Dodcott-cum-Wilkesley's web
site. The site is created using [[https://github.com/getpelican/pelican][Pelican]]. This repository should
contain all the components necessary to re-create the site. It also
contains all the sites content and the history of every change made.

* Contributing.
If you would like something published on the site, please send your
contribution to editor@dodcott.org. Time constraints mean that I can
only accept submissions by email in plain text.

I am happy to include items publicising an event, or a local
business. If you want to include a picture, please email me in advance
so we can discuss the best method of sending the picture. My email
will automatically discard messages that contain large attachments.

If you think that you, your children, or your school would like to
help build and extend the site, some very basic instructions are to be found in
"Running the Site on Your Own Computer". If you need more detailed
help, please contact me at ian@manor-farm.org. I am happy to help
getting you started.

* Design Philosophy.
The site is built using a tool that generates static html. Thus there
is no need to set up and maintain a database and the site is not vulnerable to
the sort of attacks that can affect sites built using php. Moving the
site to another host is simply a matter of copying the files.

Content can be added in a number of simple text formats including
[[http://daringfireball.net/projects/markdown/][Markdown]] making it easy for users to contribute. The site is themeable
with a wide variety of [[https://github.com/getpelican/pelican-themes][themes]] available.

With the exception of pdf files, which are hosted on Google Documents
all the content and history is available on Github, ensuring
transparency. Anyone wanting to obtain a copy of the site which includes all the
history of the changes made to the site can do so by cloning this repository.

* Running the Site on Your Own Computer.
This is a very brief guide to getting the site installed and running
on your own computer. This guide assumes that you have a working
knowledge of how to use git and python. I am currently using Python
2.7, although you should be able to use Python 3.x (not well tested).

I am building the site on a computer running Linux. However, this
guide should work if you are using a Mac. Windows users should also be
able to install and run the site locally, as all the tools used are
available in Windows. However, I don't have a computer running Windows
to test this with. If enough people running Windows want to contribute
to development, I would be happy to install Windows in a virtual
machine and provide more specific help.

Here are some very brief, non comprehensive, instructions for anyone
who wants to download the site and run it on their own computer. If
you want to try this yourself and need more help, please free to
contact me.

** Basic List of Things You Need.
   Note all the software you need is Open Source and free.

- [[http://python.org][Python]] . You need the latest 2.x version, not a version 2.x.
- [[http://git-scm.com/][Git]]. A version control system.
- A decent text editor, NOT a word processor. If you are using Windows
  Notepad++ is supposed to be good.
- An ssh client. If you are using Mac or Linux you already have one
  built in. Windows users can download [[http://www.chiark.greenend.org.uk/~sgtatham/putty/][Putty]].
- A [[https://github.com][Github]] account. This isn't essential, but will make your life
  easier. It's free to join and use.

** Using Python in a VirtualEnv.
I would strongly recommend that you set up Python in a [[https://wiki.archlinux.org/index.php/Virtualenv][VirtualEnv]]
. This creates an isolated environment in which you can install
packages without interfering with your computer's own installed Python
packages.

** Installing Nikola.
It is strongly recommended that you use the pip software management tool, which
is built into Python.

From a command prompt run:

pip install nikola.

You will also need to install the Markdown package for Python:

** Using Nikola.
The full documentation for Nikola is available at [[https://getnikola.com/handbook.html][Nikola handbook]].


** Getting the Source Code.
You need to download the source code and all the content for the site
to your local computer. You need to use git to make a clone of the
repository on the Github web site.

: git clone git@github.com:geekinthesticks/dodcott-cum-wilkesley.git

This will create a copy of everything on Github to a directory called dodcott-cum-wilkesley.


** Running the Site on Your Own Computer.
Once you have used git  to clone the site to your local computer,  change
to the  subdirectory:

#+begin_src sh
cd dodcott.org.pelican           dodcott.org.pelican/nikola/dodcott.org
#+end_src

Building the site:

#+begin_src sh
nikola build
#+end_src

will generate all the content in the output subdirectory. This
contains everything that is on the web site.

You can use Python's built in web server to view the site on your
local machine:

#+begin_src sh
nikola serve
#+end_src

You can view the site by opening http://localhost:8000 in your web
browser.
